name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
assignees:
  - mackysoft
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: XPool Version
      description: What version of XPool were you running?
      placeholder: ex. 0.1.0
    validations:
      required: true
  - type: input
    id: unity-version
    attributes:
      label: Unity Version
      description: What version of Unity were you running?
      placeholder: ex. 2020.3.24f1